#!/bin/bash
#SBATCH --job-name=timeseriespull
#SBATCH -o /projects/niblab/experiments/chocolate_milkshake/data/error_files/timepull_out_%A.txt
#SBATCH -e /projects/niblab/experiments/chocolate_milkshake/data/error_files/timepull_beta_err_%A.txt



/projects/niblab/modules/software/miniconda3/miniconda3/bin/python3 /projects/niblab/experiments/chocolate_milkshake/data/betaseries/timeseries_roi_pull.py ${1}
