#!/bin/bash
#SBATCH --job-name=betaseriesf1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 24:00:00
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/experiments/chocolate_milkshake/data/error_files/feat1_beta_%a_%A_out.txt
#SBATCH -e /projects/niblab/experiments/chocolate_milkshake/data/error_files/feat1_beta_%a_%A_err.txt

TASK=$1

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    sub="sub-00${SLURM_ARRAY_TASK_ID}"
elif [ ${SLURM_ARRAY_TASK_ID} -lt 100 ]; then
    sub="sub-0${SLURM_ARRAY_TASK_ID}"
else
    sub="sub-${SLURM_ARRAY_TASK_ID}"
fi

MILKSHAKES=(/projects/niblab/experiments/chocolate_milkshake/bids/derivatives/preprocessed/sub-*/ses-1/analysis/beta/task-*/design_files/*_${TASK}_*.fsf)


for f in ${MILKSHAKES[@]}; do
    echo ${f}
    /projects/niblab/modules/software/fsl/5.0.10/bin/feat $f &
done


