#!/bin/bash
#
#SBATCH --job-name=F3_CHOCO
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 1:30:00
#SBATCH --mem-per-cpu 25000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/feat3_%a_%A_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/feat3_%a_%A_err.txt


/projects/niblab/modules/software/fsl/5.0.10/bin/feat /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/group_ana/ses-1/cope_${SLURM_ARRAY_TASK_ID}.fsf &
